// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rerogttfayeamgmxwdpm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcm9ndHRmYXllYW1nbXh3ZHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjM3MDQsImV4cCI6MjA2MDI5OTcwNH0.IZXXB135URVbzLEAJr9qKibvXydVKPtVh3wmUOe-lEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);